// Genres constants based on the order used in OrderSubjects
// Export only the names for selection (signup step)
export const GENRES = [
  "Fantasy",
  "Science fiction",
  "Fiction",
  "Romance",
  "Young adult",
  "Young adult fiction",
  "Adventure",
  "Action",
  "Thriller",
  "Mystery",
  "Crime",
  "Detective",
  "Horror",
  "Drama",
  "Poetry",
  "Short stories",
  "Historical fiction",
  "History",
  "Biography",
  "Autobiography",
  "Memoir",
  "Non-fiction",
  "Classic literature",
  "Children's literature",
  "Middle grade",
  "Self-help",
  "Psychology",
  "Philosophy",
  "Spirituality",
  "Religion",
  "Mythology",
  "Magic",
  "Supernatural",
  "Dystopia",
  "Utopia",
  "Post-apocalyptic",
  "War",
  "Politics",
  "Social issues",
  "LGBTQ+",
  "Friendship",
  "Family",
  "Relationships",
  "Coming of age",
  "Education",
  "Science",
  "Technology",
  "Artificial intelligence",
  "Space",
  "Time travel",
  "Environment",
  "Nature",
  "Animals",
  "Sports",
  "Travel",
  "Art",
  "Music",
  "Culture",
  "Humor",
  "Satire",
  "Cooking",
  "Health",
  "Medicine",
  "Economics",
  "Business",
];

// See note in `app/constants/book.js` — add a no-op default export so Expo Router
// doesn't treat this as a missing route component.
export default function GenresConstantsRoutePlaceholder() {
  return null;
}
